global:
 scrape_interval: 10s

scrape_configs:
 - job_name: 'prometheus_master'
   scrape_interval: 5s
   static_configs:
     - targets: ['localhost:9090']
 - job_name: 'pcrf_node_exporter_centos'
   scrape_interval: 5s
   static_configs:
     - targets: ['192.168.110.120:9100']
       labels:
         site: prod
 - job_name: 'pcrf_postgres_exporter'
   static_configs:
     - targets: ['192.168.110.120:9187']
       labels:
         site: prod
 - job_name: 'pcrf_jmx_eporter'
   static_configs:
     - targets: ['192.168.110.120:9011']
       labels:
         site: prod
 - job_name: 'blackbox_http'
   metrics_path: /probe
   params:
     module: [http_2xx]
   static_configs:
     - targets:
       - http://192.168.110.120:8080/pcrf.admin
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 192.168.110.120:9115

remote_write:
 - url: http://localhost:8428/api/v1/write

remote_read:
 - url: http://localhost:8428/api/v1/read

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

rule_files:
  - "/etc/prometheus/alert.rules"